/* Automatically generated by wasm2c */
#ifndef RAFFLE_GO_H_GENERATED_
#define RAFFLE_GO_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_env;
struct w2c_wasi__snapshot__preview1;

typedef struct w2c_raffle0x2Dgo {
  struct w2c_env* w2c_env_instance;
  struct w2c_wasi__snapshot__preview1* w2c_wasi__snapshot__preview1_instance;
  u32 w2c_g0;
  u64 w2c_g1;
  u64 w2c_g2;
  u64 w2c_g3;
  u64 w2c_g4;
  u64 w2c_g5;
  u64 w2c_g6;
  u32 w2c_g7;
  wasm_rt_memory_t w2c_memory;
  wasm_rt_funcref_table_t w2c_T0;
} w2c_raffle0x2Dgo;

void wasm2c_raffle0x2Dgo_instantiate(w2c_raffle0x2Dgo*, struct w2c_env*, struct w2c_wasi__snapshot__preview1*);
void wasm2c_raffle0x2Dgo_free(w2c_raffle0x2Dgo*);
wasm_rt_func_type_t wasm2c_raffle0x2Dgo_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* import: 'env' 'log_message' */
void w2c_env_log_message(struct w2c_env*, u32, u32);

/* import: 'env' 'sys_call' */
u32 w2c_env_sys_call(struct w2c_env*, u32, u32, u32, u32);

/* import: 'wasi_snapshot_preview1' 'args_get' */
u32 w2c_wasi__snapshot__preview1_args_get(struct w2c_wasi__snapshot__preview1*, u32, u32);

/* import: 'wasi_snapshot_preview1' 'args_sizes_get' */
u32 w2c_wasi__snapshot__preview1_args_sizes_get(struct w2c_wasi__snapshot__preview1*, u32, u32);

/* import: 'wasi_snapshot_preview1' 'clock_time_get' */
u32 w2c_wasi__snapshot__preview1_clock_time_get(struct w2c_wasi__snapshot__preview1*, u32, u64, u32);

/* import: 'wasi_snapshot_preview1' 'environ_get' */
u32 w2c_wasi__snapshot__preview1_environ_get(struct w2c_wasi__snapshot__preview1*, u32, u32);

/* import: 'wasi_snapshot_preview1' 'environ_sizes_get' */
u32 w2c_wasi__snapshot__preview1_environ_sizes_get(struct w2c_wasi__snapshot__preview1*, u32, u32);

/* import: 'wasi_snapshot_preview1' 'fd_close' */
u32 w2c_wasi__snapshot__preview1_fd_close(struct w2c_wasi__snapshot__preview1*, u32);

/* import: 'wasi_snapshot_preview1' 'fd_fdstat_get' */
u32 w2c_wasi__snapshot__preview1_fd_fdstat_get(struct w2c_wasi__snapshot__preview1*, u32, u32);

/* import: 'wasi_snapshot_preview1' 'fd_fdstat_set_flags' */
u32 w2c_wasi__snapshot__preview1_fd_fdstat_set_flags(struct w2c_wasi__snapshot__preview1*, u32, u32);

/* import: 'wasi_snapshot_preview1' 'fd_prestat_dir_name' */
u32 w2c_wasi__snapshot__preview1_fd_prestat_dir_name(struct w2c_wasi__snapshot__preview1*, u32, u32, u32);

/* import: 'wasi_snapshot_preview1' 'fd_prestat_get' */
u32 w2c_wasi__snapshot__preview1_fd_prestat_get(struct w2c_wasi__snapshot__preview1*, u32, u32);

/* import: 'wasi_snapshot_preview1' 'fd_write' */
u32 w2c_wasi__snapshot__preview1_fd_write(struct w2c_wasi__snapshot__preview1*, u32, u32, u32, u32);

/* import: 'wasi_snapshot_preview1' 'poll_oneoff' */
u32 w2c_wasi__snapshot__preview1_poll_oneoff(struct w2c_wasi__snapshot__preview1*, u32, u32, u32, u32);

/* import: 'wasi_snapshot_preview1' 'proc_exit' */
void w2c_wasi__snapshot__preview1_proc_exit(struct w2c_wasi__snapshot__preview1*, u32);

/* import: 'wasi_snapshot_preview1' 'random_get' */
u32 w2c_wasi__snapshot__preview1_random_get(struct w2c_wasi__snapshot__preview1*, u32, u32);

/* import: 'wasi_snapshot_preview1' 'sched_yield' */
u32 w2c_wasi__snapshot__preview1_sched_yield(struct w2c_wasi__snapshot__preview1*);

/* export: '_start' */
void w2c_raffle0x2Dgo_0x5Fstart(w2c_raffle0x2Dgo*);

/* export: 'init_contract' */
void w2c_raffle0x2Dgo_init_contract(w2c_raffle0x2Dgo*);

/* export: 'upgrade' */
void w2c_raffle0x2Dgo_upgrade(w2c_raffle0x2Dgo*);

/* export: 'registerAll' */
void w2c_raffle0x2Dgo_registerAll(w2c_raffle0x2Dgo*);

/* export: 'raffle' */
void w2c_raffle0x2Dgo_raffle(w2c_raffle0x2Dgo*);

/* export: 'registRaffle' */
void w2c_raffle0x2Dgo_registRaffle(w2c_raffle0x2Dgo*);

/* export: 'query' */
void w2c_raffle0x2Dgo_query(w2c_raffle0x2Dgo*);

/* export: 'runtime_type' */
u32 w2c_raffle0x2Dgo_runtime_type(w2c_raffle0x2Dgo*);

/* export: 'deallocate' */
void w2c_raffle0x2Dgo_deallocate(w2c_raffle0x2Dgo*, u32);

/* export: 'allocate' */
u32 w2c_raffle0x2Dgo_allocate(w2c_raffle0x2Dgo*, u32);

/* export: 'memory' */
wasm_rt_memory_t* w2c_raffle0x2Dgo_memory(w2c_raffle0x2Dgo* instance);

#ifdef __cplusplus
}
#endif

#endif  /* RAFFLE_GO_H_GENERATED_ */
